<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>994a2fb5-5219-4a77-94e6-ead6b295f47e</elementGuidId>
    <imagePath></imagePath>
    <name>button_save</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[3]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Save')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^Save$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save</value>
        <webElementGuid>7fc80acb-ce11-4d7d-afbe-e22464548198</webElementGuid>
    </webElementProperties>
</WebElementEntity>