<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5563d91c-d6e2-4410-a18b-72e4e7ceb3a1</elementGuidId>
    <imagePath></imagePath>
    <name>button_logOut</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/ul[1]/li[5]/div[1]/button[7]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>button:nth-of-type(7)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Log out')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Log out\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Log out</value>
        <webElementGuid>9aa4c449-6750-4308-950d-f2fdcbfc06ab</webElementGuid>
    </webElementProperties>
</WebElementEntity>