<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d506fdc5-bc21-4c45-b41f-7ce4ec0ec77f</elementGuidId>
    <imagePath></imagePath>
    <name>button_addProject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-primary\ btn-sm\ primary-action"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Add Project')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"page-List\\/Project\\/List\"] &gt; .page-head &gt; .container &gt; .row &gt; div:nth-child(2) &gt; .standard-actions &gt; button:nth-child(5)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add Project</value>
        <webElementGuid>9aa4c449-6750-4308-950d-f2fdcbfc06ab</webElementGuid>
    </webElementProperties>
</WebElementEntity>