<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5981839b-2740-4dee-a54a-e92b51a26ff4</elementGuidId>
    <imagePath></imagePath>
    <name>link_dailyTimesheetSummary</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[12]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Daily Timesheet Summary') and equals(@href,'{{url}}Daily%20Timesheet%20Summary') and equals(@type,'Link') and equals(@text,'Daily Timesheet Summary
            You need to create these first:
            Timesheet')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"Daily Timesheet Summary\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}Daily%20Timesheet%20Summary</value>
        <webElementGuid>fd39c8ba-5a2c-4c7f-8e6b-829c077120cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Daily Timesheet Summary
        You need to create these first:
        Timesheet</value>
        <webElementGuid>fd39c8ba-5a2c-4c7f-8e6b-829c077120cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Daily Timesheet Summary</value>
        <webElementGuid>fd39c8ba-5a2c-4c7f-8e6b-829c077120cb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>Link</value>
        <webElementGuid>fd39c8ba-5a2c-4c7f-8e6b-829c077120cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>