<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b325cc96-65f2-4d04-b33f-e48e15bc14b9</elementGuidId>
    <imagePath></imagePath>
    <name>div_day8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[2]/div[1]/div[1]/div[2]/div[9]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .datepicker--content &gt; .datepicker--days &gt; .datepicker--cells &gt; div:nth-child(9)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>