<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1c7994af-3413-46ce-ad82-fe4ad3148afd</elementGuidId>
    <imagePath></imagePath>
    <name>button_addTimesheet</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Add Timesheet')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"page-List\\/Timesheet\\/List\"] &gt; .page-head &gt; .container &gt; .row &gt; div:nth-child(2) &gt; .standard-actions &gt; button:nth-child(5)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add Timesheet</value>
        <webElementGuid>417d794e-babd-456e-8064-e70979906513</webElementGuid>
    </webElementProperties>
</WebElementEntity>