<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25589922-dbd6-4928-b2d0-8c8d6e89ce16</elementGuidId>
    <imagePath></imagePath>
    <name>button_logOut</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/ul[1]/li[5]/div[1]/button[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Log out')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Log out\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Log out</value>
        <webElementGuid>e6a3bc03-f591-4eb6-b059-2bca15c8283d</webElementGuid>
    </webElementProperties>
</WebElementEntity>